//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AccountTransaction
{
	public virtual GUID UserID
	{
		get;
		set;
	}

	public virtual double Amount
	{
		get;
		set;
	}

	public virtual DateTime DateTime
	{
		get;
		set;
	}

}

