//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ItemsForBorrow
{
	public virtual Int64 ItemID
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public virtual double Price
	{
		get;
		set;
	}

	public virtual List<ItemsForBorrow> GetItems()
	{
		throw new System.NotImplementedException();
	}

	public virtual void BorrowItem(object User_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAllBorrowedItems:List<ItemsForBorrow>(object User_ID)
	{
		throw new System.NotImplementedException();
	}

}

