//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ItemsForSell
{
	public virtual GUID ItemID
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public virtual double Price
	{
		get;
		set;
	}

	public virtual void FillTheStore(object SKUID)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<ItemsForSell> GetAllItems()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<ItemsForSell> GetReminderItems()
	{
		throw new System.NotImplementedException();
	}

	public virtual void BuyItems()
	{
		throw new System.NotImplementedException();
	}

}

