//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual GUID User_ID
	{
		get;
		set;
	}

	public virtual string FirstName
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual object QR_Code
	{
		get;
		set;
	}

	public virtual DateTime Birthday
	{
		get;
		set;
	}

	public virtual string RFID
	{
		get;
		set;
	}

	public virtual double CurrentBalance
	{
		get;
		set;
	}

	public virtual string Email
	{
		get;
		set;
	}

	public virtual boolean CampingAccess
	{
		get;
		set;
	}

	public virtual List<ItemsForBorrow> BorrowedItems
	{
		get;
		set;
	}

	public virtual List<AccountTransaction> AccountTransactions
	{
		get;
		set;
	}

	public virtual IEnumerable<AccountTransaction> AccountTransaction
	{
		get;
		set;
	}

	public virtual void GetInfo(object User_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AccessToCamping(object User_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void MatchRFID(object User_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Deposit(object User_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void WithDraw(object User_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAllAccountTransactions(object User_ID)
	{
		throw new System.NotImplementedException();
	}

}

