//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Camping
{
	public virtual GUID CampingID
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public virtual double Price
	{
		get;
		set;
	}

	public virtual boolean Access
	{
		get;
		set;
	}

	public virtual boolean ReservationMade
	{
		get;
		set;
	}

	public virtual void AccessToCamping()
	{
		throw new System.NotImplementedException();
	}

}

